<?php

namespace Bigfoot\Bundle\NavigationBundle\Entity\Menu\Item;

use Doctrine\ORM\EntityRepository;

/**
 * AttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeRepository extends EntityRepository
{
}
