<?php

namespace Bigfoot\Bundle\NavigationBundle\Entity;

use Gedmo\Sortable\Entity\Repository\SortableRepository as EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
}
