<?php

namespace Bigfoot\Bundle\NavigationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemParameterRepository extends EntityRepository
{
}
