<?php

namespace Bigfoot\Bundle\NavigationBundle\Entity\Route;

use Doctrine\ORM\EntityRepository;

/**
 * ParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterRepository extends EntityRepository
{
    /**
     * findOneByRouteName
     */
    public function findOneByRouteName($route, $name)
    {
        return $this
            ->createQueryBuilder('p')
            ->where('p.route = :route')
            ->andWhere('p.name = :name')
            ->setParameter('route', $route)
            ->setParameter('name', $name)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
